tomaka/redshirt

interfaces/interface/src/lib.rs, modules/Cargo.lock, modules/ipfs/Cargo.toml, modules/ipfs/src/lib.rs, modules/ipfs/src/main.rs
The `main.rs` file is now clean. The `lib.rs` has a good API starting point.
=> Draft for better API for "ipfs"

Cargo.lock, hosted/wasi/Cargo.toml, hosted/wasi/src/lib.rs
=> Draft for WASI clock function

core/src/system.rs, hosted/cli/src/main.rs, hosted/kernel/src/main.rs
=> Slightly change the System initialization

core/src/scheduler/ipc.rs, core/src/scheduler/processes.rs, core/src/system.rs
=> Use tid() instead of id()

Cargo.lock, core/Cargo.toml, core/src/module.rs
=> Use wat instead of wabt

kernel/standalone/src/main.rs
=> Enable no_std for kernel/standalone

kernel/standalone/src/arch/x86_64/boot.S
At some point I mistakenly increased this value thinking it was the stack size.
=> Decrease stack alignment

kernel/standalone/src/arch/x86_64.rs, kernel/standalone/src/main.rs
Removes platform-specific code from main.rs
=> Add arch::halt and call it!

core/src/scheduler/ipc.rs, interfaces/syscalls/src/block_on.rs, interfaces/syscalls/src/ffi.rs, interfaces/syscalls/src/interface_message.rs, interfaces/syscalls/src/lib.rs, modules/ipfs/src/main.rs, modules/x86-stdout/src/main.rs
=> Add a ProcessClosed variant to messages

Cargo.lock, interfaces/hardware/Cargo.toml, interfaces/hardware/src/lib.rs, kernel/hardware/Cargo.toml, kernel/standalone/Cargo.toml, modules/Cargo.lock, modules/x86-stdout/Cargo.toml
=> Add reading ops to the hardware interface

Cargo.lock, kernel/hardware/Cargo.toml, kernel/hardware/src/arch.rs, kernel/hardware/src/arch/x86_64.rs, kernel/hardware/src/arch/x86_64/interrupts.rs, kernel/hardware/src/lib.rs
Infrastructure for interrupts handling.
=> Add interrupts table to hardware

kernel/standalone/src/arch/x86_64.rs, kernel/standalone/src/mem_alloc.rs
=> Properly initialize the heap on x86_64

Cargo.lock, kernel/standalone/Cargo.toml, kernel/standalone/src/arch/arm.rs, kernel/standalone/src/kernel.rs, kernel/standalone/src/main.rs, kernel/standalone/src/random.rs, kernel/standalone/src/random/native.rs, kernel/standalone/src/random/rng.rs, kernel/standalone/src/time.rs
I'm not a cryptographer, but here's some crypto.
=> Add native randomness

Cargo.lock, core/src/scheduler/ipc.rs, interfaces/syscalls/Cargo.toml, interfaces/syscalls/src/emit.rs, interfaces/syscalls/src/ffi.rs, modules/Cargo.lock
=> Change emit_message syscall to allow split messages

core/src/scheduler/ipc.rs, interfaces/syscalls/src/emit.rs
I have no idea how it worked before.
=> Fix bad message emission

.github/workflows/ci.yml
=> Add CI build for Windows

core/src/scheduler/ipc.rs
=> Fix ReservedPidInterfaceMessage emitted for non-reserved PIDs

interfaces/hardware/src/lib.rs, modules/x86-log/src/main.rs
It doesn't work properly because of #209, but it works enough for me to test and improve.
=> Refactor x86-log

core/src/native/collection.rs, core/src/native/traits.rs, core/src/system.rs, kernel/cli/src/main.rs, kernel/standalone/src/kernel.rs
cc #1 
After #216, we might as well finish the job.
=> Make System methods take &self

Cargo.lock, kernel/standalone/Cargo.toml
Follow-up to https://github.com/phil-opp/linked-list-allocator/pull/18
=> Bump linked-list-allocator

Cargo.lock, core/Cargo.toml, core/src/module.rs, kernel/standalone/Cargo.toml, kernel/standalone/src/random/rng.rs
Bleeding edge :crossed_swords: :rocket:
=> Use blake3

modules/p2p-loader/Dockerfile
I'm unfortunately unable to test this locally :(
=> Use Debian in the Dockerfile

.github/workflows/ci.yml, Cargo.lock, kernel/standalone/Cargo.toml, kernel/standalone/src/main.rs
Close #164 
Thank you @phil-opp!
=> Make it compile on nightly again

Cargo.lock, Cargo.toml, interfaces/log/src/lib.rs, kernel/cli/Cargo.toml, kernel/cli/src/main.rs, kernel/hosted-tcp/Cargo.toml, kernel/hosted-tcp/src/lib.rs, modules/Cargo.lock, modules/http-server/Cargo.toml, modules/http-server/src/main.rs
Make it work again
EDIT: also fixes #247
=> Restore hosted-tcp

Cargo.lock, modules/Cargo.lock
Done using https://docs.rs/cargo-lock
Reference: https://github.com/rust-lang/cargo/pull/7070
=> Switch lock files to version 2

Cargo.lock, kernel/standalone/Cargo.toml, kernel/standalone/src/arch/arm.rs, kernel/standalone/src/arch/x86_64.rs, kernel/standalone/src/arch/x86_64/apic.rs, kernel/standalone/src/arch/x86_64/interrupts.rs, kernel/standalone/src/kernel.rs, kernel/standalone/src/random/rng.rs, kernel/standalone/src/time.rs
=> Add an x86 native implementation of the time interface

core/src/scheduler/processes.rs, interfaces/log/src/lib.rs, interfaces/random/src/lib.rs, modules/p2p-loader/src/tcp_transport.rs, modules/third-party/getrandom/src/lib.rs
Including a pretty stupid/serious bug with the randomness not working.
=> Fix some warnings

modules/Cargo.lock, modules/third-party/getrandom/Cargo.toml, modules/third-party/getrandom/src/lib.rs
Should fix the node deployment failing.
=> Fix getrandom doing a redshirt syscalls on non-wasm

interfaces/syscalls/src/block_on.rs, interfaces/syscalls/src/emit.rs, interfaces/syscalls/src/ffi.rs, interfaces/syscalls/src/interface_message.rs
=> Make syscalls crate compile on non-wasm

.github/workflows/ci.yml, modules/arm-log/src/main.rs, modules/hello-world/src/main.rs, modules/http-server/src/main.rs, modules/ne2000/src/device.rs, modules/ne2000/src/main.rs, modules/p2p-loader/src/lib.rs, modules/rpi-framebuffer/src/mailbox.rs, modules/rpi-framebuffer/src/main.rs, modules/rpi-framebuffer/src/property.rs, modules/stub/src/main.rs, modules/x86-log/src/main.rs, modules/x86-pci/build.rs, modules/x86-pci/src/main.rs
=> Fix rustfmt no checking everywhere

Cargo.lock, core/Cargo.toml, core/src/scheduler/extrinsics.rs, interfaces/syscalls/Cargo.toml, interfaces/syscalls/src/emit.rs, kernel/standalone/Cargo.toml, kernel/standalone/src/random/rng.rs, modules/Cargo.lock, modules/rpi-framebuffer/Cargo.toml, modules/rpi-framebuffer/src/main.rs
=> Remove byteorder from the code

core/src/scheduler.rs, core/src/scheduler/ipc.rs, core/src/system.rs, kernel/cli/src/main.rs, kernel/standalone/src/kernel.rs
Some basic clean up of the `System`.
=> Some work on System

core/src/extrinsics/wasi.rs
It turns out that memcpying structs to the Wasi program's memory wasn't the greatest idea, since the pointer size is different.
This removes the `unsafe` code from the Wasi handlers.
Also adds a stub for `ftell`.
=> More Wasi work and fixing

core/src/extrinsics/wasi.rs
=> Make Wasi finally work properly for DOOM

interfaces/syscalls/src/emit.rs, interfaces/syscalls/src/ffi.rs
The ABI stays the same, this is a very small change.
=> Fix pointer type in emit_message ffi

Cargo.lock, core/Cargo.toml, core/src/extrinsics/wasi.rs, core/src/id_pool.rs, core/src/native/collection.rs, interfaces/syscalls/Cargo.toml, interfaces/syscalls/src/block_on.rs, kernel/standalone/Cargo.toml, kernel/standalone/src/arch/arm/time_arm.rs, kernel/standalone/src/arch/x86_64/apic/timers.rs, kernel/standalone/src/hardware.rs, kernel/standalone/src/time.rs, modules/Cargo.lock
As `spin` is unmaintained: https://github.com/RustSec/advisory-db/blob/master/crates/spin/RUSTSEC-2019-0031.toml
=> Replace spin::Mutex with spinning_top::Spinlock

Cargo.lock, Cargo.toml, interfaces/framebuffer/Cargo.toml, interfaces/framebuffer/src/ffi.rs, interfaces/framebuffer/src/lib.rs, interfaces/random/src/lib.rs
=> Add a framebuffer interface

core/src/extrinsics.rs, core/src/extrinsics/log_calls.rs, core/src/extrinsics/wasi.rs, core/src/lib.rs, core/src/scheduler/extrinsics.rs, core/src/scheduler/extrinsics/calls.rs, core/src/scheduler/ipc.rs, core/src/scheduler/processes.rs, core/src/scheduler/tests/basic_module.rs, core/src/scheduler/vm.rs, core/src/signature.rs, core/src/wasm_value.rs
So that we abstract over wasmi.
=> Wrap around wasmi types

core/src/system.rs
As it may be unavailable on 32-bits platforms.
=> Don't use AtomicU64

.github/workflows/ci.yml, Cargo.lock, README.md, kernel/standalone/Cargo.toml, kernel/standalone/src/arch/x86_64/ap_boot.rs
Update for the latest changes to the alloc API.
=> Update to nightly-2020-04-10

core/src/scheduler/extrinsics.rs
When a thread executing a custom extrinsic emits a message, it immediately transitions to "waiting" without reporting this transition in the API.
=> Fix extrinsics.rs not reporting waiting thread

.github/node-deploy-kube-config.yml, modules/Cargo.lock, modules/p2p-loader/Cargo.toml, modules/p2p-loader/src/bin/passive-node.rs, modules/p2p-loader/src/git_clones.rs, modules/p2p-loader/src/lib.rs
=> p2p-loader support for watching a git repo

README.md
=> Update the README for the standard modules

core/Cargo.toml, core/src/extrinsics/log_calls.rs, core/src/scheduler.rs, core/src/scheduler/ipc.rs, interfaces/interface/src/lib.rs
Removes 4 TODOs out of the 439 in total in the code :tada:
=> Fix a couple of TODOs

core/src/extrinsics/wasi.rs, interfaces/framebuffer/src/ffi.rs, interfaces/framebuffer/src/lib.rs, kernel/hosted-framebuffer/src/lib.rs
cc #323 
While this is quickly implemented, it is some work towards propagating glutin events to the guest.
=> Add keyboard inputs to framebuffer interface

interfaces/random/src/lib.rs
=> Add helper functions to random interface

core/src/id_pool.rs, core/src/lib.rs, core/src/scheduler/extrinsics/calls.rs, core/src/scheduler/ipc/notifications_queue.rs, interfaces/syscalls/src/block_on.rs, interfaces/syscalls/src/emit.rs, interfaces/syscalls/src/ffi.rs, interfaces/syscalls/src/interface_message.rs, interfaces/syscalls/src/lib.rs
It is an invalid value, but until now we didn't check for it.
=> Forbid the value 1 for MessageIds

README.md, docs/authorizations.md, docs/interfaces.md, docs/introduction.md, docs/messages.md
=> Add a lot of documentation

interfaces/syscalls/src/block_on.rs, interfaces/syscalls/src/interface_message.rs, interfaces/syscalls/src/response.rs
=> Make Futures work with now_or_never

Cargo.lock, kernel/standalone/Cargo.toml, kernel/standalone/src/random/rng.rs
=> Prefer using RdSeed if available

interfaces/pci/src/lib.rs, kernel/standalone/src/arch/x86_64.rs, modules/Cargo.lock, modules/ne2000/Cargo.toml, modules/ne2000/src/device.rs, modules/ne2000/src/main.rs, modules/pci-printer/build.rs
=> Make the ne2000 driver work

modules/p2p-loader/src/lib.rs
I must have screwed up something, because this isn't supposed to change.
=> Update bootnode IP

modules/Cargo.lock
Another screw-up extracted from #97 
I had accidentally erased the dependency overwrite.
=> Fix time dependency

kernel/standalone/src/future_channel.rs, kernel/standalone/src/hardware.rs, kernel/standalone/src/klog/native.rs, kernel/standalone/src/main.rs, kernel/standalone/src/pci/native.rs, kernel/standalone/src/random/native.rs, kernel/standalone/src/time.rs
Fix #462 
Need to update all the standalone native programs before merging.
=> Use a no_std implementation of channels

Cargo.lock, interfaces/ethernet/src/interface.rs, interfaces/tcp/Cargo.toml, interfaces/tcp/src/ffi.rs, interfaces/tcp/src/lib.rs, kernel/hosted-tcp/src/lib.rs, modules/Cargo.lock
Makes the TCP interface cleaner and more in phase with what TCP on other operating systems does.
Plus a small unrelated fix in the ethernet interface.
=> Improve the TCP interface

interfaces/ethernet/src/interface.rs, interfaces/hardware/src/malloc.rs, kernel/standalone-builder/src/emulator.rs, kernel/standalone/src/kernel.rs, modules/Cargo.lock, modules/Cargo.toml, modules/e1000/Cargo.toml, modules/e1000/src/device.rs, modules/e1000/src/main.rs, modules/network-manager/src/manager.rs
It is the default emulated device basically everywhere.
I'll remove the ne2000 driver afterwards.
=> Add a e1000 driver

modules/p2p-loader/src/lib.rs
=> Fix the bootnode IP again

kernel/standalone/src/future_channel.rs
=> Fix panic in unbounded receiver

kernel/standalone-builder/res/specs/x86_64-multiboot2.ld, kernel/standalone-builder/src/image.rs
Tweaks the multiboot2 header to ask GRUB to setup a graphics mode for us.
=> Start with graphics mode on

Cargo.lock, core-proc-macros/Cargo.toml, core-proc-macros/src/lib.rs, core/Cargo.toml, core/src/lib.rs
Since this is now supported by stable Rust.
=> Remove using proc_macro_hack

Cargo.lock, Cargo.toml, core/Cargo.toml, core/src/system.rs, interfaces/kernel-debug/Cargo.toml, interfaces/kernel-debug/src/ffi.rs, interfaces/kernel-debug/src/lib.rs, kernel/cli/src/main.rs, kernel/standalone/src/kernel.rs, modules/Cargo.lock, modules/Cargo.toml, modules/kernel-debug-printer/Cargo.toml, modules/kernel-debug-printer/src/main.rs
=> Add a kernel debug interface

kernel/standalone/src/kernel.rs, modules/p2p-loader/src/bin/modules-loader.rs, modules/p2p-loader/src/lib.rs
The IP addresses have changed again. cc #482 
Other than that, the peer-to-peer loader appears to be working :tada:
=> Fix peer-to-peer loader again

kernel/standalone-builder/src/image.rs
Otherwise it doesn't boot on my real machine
=> Restore loading GRUB video drivers

core/src/system.rs
It is more idiomatic to use counters rather than gauges, as it guarantees that we haven't lost any information due to the poll rate being too low.
=> Split num_processes into multiple counters

kernel/standalone/src/kernel.rs, modules/Cargo.lock, modules/Cargo.toml, modules/dummy-system-time/Cargo.toml, modules/dummy-system-time/src/main.rs
cc https://github.com/tomaka/redshirt/issues/542
=> Add dummy-system-time process

Cargo.lock, Cargo.toml, interfaces/disk/Cargo.toml, interfaces/disk/src/disk.rs, interfaces/disk/src/ffi.rs, interfaces/disk/src/lib.rs
=> Add a disk interface

kernel/standalone/src/main.rs
=> Remove the `panic_info_message` feature

modules/Cargo.lock, modules/compositor/Cargo.toml, modules/compositor/src/lib.rs, modules/compositor/src/main.rs, modules/compositor/src/rect.rs
Turns the draft into something a bit less of a draft.
Framebuffers rendering is now supposed to work.
I think the compositor is unfortunately crashing, and it can't really be debugged without https://github.com/tomaka/redshirt/issues/682.
=> Work on the compositor

Cargo.lock, core/Cargo.toml, core/src/id_pool.rs, kernel/standalone/src/random/rng.rs
ChaCha20 is completely fine when it comes to seeding itself.
=> Address comments about random numbers

interfaces/kernel-log/src/ffi.rs, kernel/standalone-builder/src/emulator.rs, kernel/standalone/src/arch/arm.rs, kernel/standalone/src/arch/riscv.rs, kernel/standalone/src/arch/x86_64.rs, kernel/standalone/src/klog/logger.rs
=> Make kernel output logs to serial port on x86

modules/vga-vbe/src/interpreter.rs, modules/vga-vbe/src/main.rs
=> Implement ADC opcode in interpreter

.github/workflows/ci.yml, kernel/standalone-builder/Cargo.lock, kernel/standalone-builder/Cargo.toml, kernel/standalone-builder/src/bin/main.rs, kernel/standalone-builder/src/emulator.rs, kernel/standalone-builder/src/lib.rs, kernel/standalone-builder/src/test.rs, kernel/standalone/src/arch/arm.rs, kernel/standalone/src/arch/riscv.rs
cc #585 
Adds an `emulator-test` command to the kernel builder.
=> Test standalone kernel on CI

.github/workflows/ci.yml
I don't actually know if this will work.
=> Simplify installation of clang on CI

kernel/core/src/system.rs, kernel/standalone/src/hardware.rs, kernel/standalone/src/kernel.rs, kernel/standalone/src/klog/native.rs, kernel/standalone/src/pci/native.rs, kernel/standalone/src/random/native.rs, kernel/standalone/src/time.rs
=> Fix race condition in external messages

kernel/core/src/scheduler/processes.rs, kernel/core/src/scheduler/processes/wakers.rs
=> Fix potential race and deadlock in processes.rs

.github/mergify.yml, .github/workflows/ci.yml, Cargo.lock, kernel-standalone-builder/src/build.rs, kernel/standalone/Cargo.toml, kernel/standalone/build.rs, kernel/standalone/src/arch/arm.rs, kernel/standalone/src/arch/arm/misc.rs, kernel/standalone/src/arch/riscv.rs, kernel/standalone/src/arch/riscv/misc.rs, kernel/standalone/src/arch/x86_64.rs, kernel/standalone/src/arch/x86_64/acpi.rs, kernel/standalone/src/arch/x86_64/ap_boot.rs, kernel/standalone/src/arch/x86_64/apic/io_apics.rs, kernel/standalone/src/arch/x86_64/boot.rs, kernel/standalone/src/arch/x86_64/executor.rs, kernel/standalone/src/arch/x86_64/interrupts.rs, kernel/standalone/src/lib.rs, rust-toolchain
Updates Rust version to 2022-01-14
=> Make it compile again
