tomaka/redshirt

Cargo.lock
Cargo.toml
interfaces/tcp/Cargo.toml
interfaces/window/Cargo.toml
interfaces/window/src/ffi.rs
interfaces/window/src/lib.rs
kernel/Cargo.toml
kernel/src/main.rs
modules/Cargo.lock
modules/vulkan-triangle/Cargo.toml
modules/vulkan-triangle/src/main.rs

Adds a `window` interface library, handled by outside the VM.
Outside of the library, uses the `winit` library to spawn a window.
I'm unfortunately on Wayland, where windows don't appear before being drawn to, so I can't really test whether this works.
The control flow of `kernel/src/main.rs` is starting to be a bit messy and probably needs some cleaning up and organization.

Draft for windowing interface

---

Cargo.lock
core/Cargo.toml
core/src/scheduler/ipc.rs
core/src/signature.rs
core/src/system.rs
hosted/kernel/Cargo.toml
hosted/kernel/src/main.rs
hosted/tcp/Cargo.toml
hosted/tcp/src/lib.rs
hosted/wasi/Cargo.toml
hosted/wasi/src/lib.rs
interfaces/interface/Cargo.toml
interfaces/interface/src/lib.rs
interfaces/loader/Cargo.toml
interfaces/loader/src/lib.rs
interfaces/syscalls/Cargo.toml
interfaces/tcp/Cargo.toml
interfaces/tcp/src/lib.rs
interfaces/threads/Cargo.toml
interfaces/threads/src/lib.rs
interfaces/vulkan/Cargo.toml
interfaces/vulkan/build/main.rs
interfaces/window/Cargo.toml
interfaces/window/src/lib.rs
modules/Cargo.lock
modules/ipfs/Cargo.toml
modules/ipfs/src/main.rs
modules/ipfs/src/tcp_transport.rs
modules/vulkan-triangle/Cargo.toml
modules/vulkan-triangle/src/main.rs

Renames all the crates with the name `nametbd`. For example: `nametbd-tcp-interface`, `nametbd-wasi-hosted`, `nametbd-core`, ...
The `nametbd` is *actually* because the name is not determined, and not an ironic way to name the project. I can later do a `sed/nametbd/something/` to easily change that.

Rename all the crates

---

core/src/scheduler/ipc.rs
core/src/scheduler/processes.rs
core/src/system.rs
hosted/wasi/src/lib.rs

Instead of having `ipc.rs` keep track of the available extrinsics (i.e. functions that the WASM code can directly import and call), we move that to `processes.rs`.
The objective is to simplify a bit the code of `ipc.rs`.
From the point of view of `processes.rs`, there's no such thing as a message. All that this module is concerned about is calling functions that potentially put threads to sleep.
If we ever add some "meta-information" about an extrinsic (e.g. likelihood of thread being able to continue running, or something), then it makes sense for this to be in `processes.rs`.

Move extrinsics registration from ipc to processes

---

Cargo.lock
hosted/cli/src/main.rs
hosted/kernel/src/main.rs
hosted/tcp/Cargo.toml
hosted/tcp/src/lib.rs

One can now inject TCP messages and receive answers in parallel.

Refactor tcp-hosted to be multithreaded

---

Cargo.lock
hosted/cli/Cargo.toml
hosted/cli/src/main.rs
hosted/kernel/src/main.rs
hosted/time/Cargo.toml
hosted/time/src/lib.rs
interfaces/time/Cargo.toml
interfaces/time/src/delay.rs
interfaces/time/src/ffi.rs
interfaces/time/src/instant.rs
interfaces/time/src/lib.rs
modules/Cargo.lock
modules/ipfs/Cargo.toml
modules/ipfs/src/main.rs

Adds support for timers.
This works by having a message which receives an empty response after a certain time has elapsed.
The `nametbd-time-hosted` crate was therefore refactored.

Add support for sleeping

---

.github/workflows/ci.yml
Cargo.lock
README.md
core/src/scheduler/vm.rs
interfaces/syscalls/src/lib.rs
kernel/cli/build.rs
kernel/gui/build.rs
kernel/standalone/Cargo.toml
kernel/standalone/build.rs
kernel/standalone/src/main.rs
modules/Cargo.lock
modules/Cargo.toml
modules/hello-world/Cargo.toml
modules/hello-world/src/main.rs

(I'm not sure why there's no new line after "hello world", but that seems like a minor issue)
Rather than trying to start `ipfs` compiled for `wasm32-wasi`, which doesn't work because of #15, we start a basic `hello-world` program compiled to `wasm32-unknown-unknown` and that writes to stdout.
Also, now that we don't use a docker image for libhermit-rs anymore, restores the necessity to have the WASI target installed in order to compile.

Add a hello world for the freestanding kernel

---

Cargo.lock
Cargo.toml
interfaces/random/Cargo.toml
interfaces/random/src/ffi.rs
interfaces/random/src/lib.rs
kernel/cli/src/main.rs
kernel/hosted-tcp/src/lib.rs
kernel/hosted-time/src/lib.rs
kernel/hosted-wasi/Cargo.toml
kernel/hosted-wasi/src/lib.rs

Close #15 
Instead of having the WASI handler directly respond to function calls, it will instead emit messages (when necessary, i.e. for time, randomness, and stdout) and answer the extrinsic call when the message response comes back.

Refactor WASI to dispatch to interfaces

---

.github/workflows/ci.yml
Cargo.lock
README.md
interfaces/time/Cargo.toml
interfaces/time/src/lib.rs
kernel/hosted-wasi/Cargo.toml
kernel/standalone/Cargo.toml
kernel/standalone/build.rs
kernel/standalone/src/main.rs

Follow-up of #92 
Now that WASI is no-std-friendly, makes the standalone kernel compile "hello-world" for WASI rather than wasm-unknown.

Make WASI work for the standalone kernel

---

Cargo.lock
interfaces/syscalls/Cargo.toml
interfaces/syscalls/src/block_on.rs
interfaces/syscalls/src/ffi.rs
interfaces/syscalls/src/lib.rs
modules/Cargo.lock

Makes `block_on` available on no_std.
We will be able to remove the `std` feature once https://github.com/rust-lang/rust/issues/56974 is fixed.

Some clean-up to syscalls-interface

---

Cargo.lock
interfaces/interface/src/lib.rs
interfaces/loader/src/lib.rs
interfaces/random/Cargo.toml
interfaces/random/src/lib.rs
interfaces/stdout/src/lib.rs
interfaces/syscalls/Cargo.toml
interfaces/syscalls/src/block_on.rs
interfaces/syscalls/src/emit.rs
interfaces/syscalls/src/interface_message.rs
interfaces/syscalls/src/lib.rs
interfaces/syscalls/src/response.rs
interfaces/tcp/src/lib.rs
interfaces/time/Cargo.toml
interfaces/time/src/lib.rs
interfaces/window/src/lib.rs
modules/Cargo.lock

Closes #90 
- Adds proper error types.
- Adds documentation.
- Removes the `std` feature. Everything is now `no_std`.

Clean up syscalls-interface

---

core/src/scheduler/ipc.rs

When sending a message to an interface registered by a program, this program wouldn't get woken up in response. This fixes it.

Fix process not resumed after message delivery

---

core/src/scheduler/ipc.rs
core/src/system.rs
interfaces/syscalls/src/emit.rs
interfaces/syscalls/src/ffi.rs

Fix #28 
Adds a flag for `emit_message` allowing the user to decide whether to allow delivering the message to be delayed waiting for an interface.
For the moment waiting for an interface effectively freezes the process. After #53 and #112, we might revisit this and let processes run in the background.

Implement lazy-loading interfaces

---

Cargo.lock
core/src/system.rs
kernel/standalone/Cargo.toml
kernel/standalone/src/kernel.rs

When a module panics, it uses the WASI interfaces to show a message on screen.
The WASI handling code then translates that into a message on the `stdout` interface.
Before this PR, this would then make the kernel panic. This PR fixes that, meaning that panicking modules now properly show a message in the console.

Panicking modules now show a message again

---

Cargo.lock
kernel/cli/Cargo.toml
kernel/hosted-wasi/src/lib.rs

New versions of Rust are apparently using a new version of WASI.
Unfortunately the environment variables system broke, and I couldn't manage to repair it. I therefore removed the `RUST_BACKTRACE=1` environment variable.

Fix WASI after Rust 1.40 upgrade

---

Cargo.lock
core/src/system.rs
kernel/cli/Cargo.toml
kernel/cli/src/main.rs
modules/.cargo/config

One can now do `cargo run -- some_wasi_file.wasm` and see it run!
Alternatively, go in a module's directory and do `cargo run --target=wasm32-wasi`.

Make the CLI kernel able to run WASM modules

---

Cargo.lock
core/src/scheduler.rs
core/src/scheduler/ipc.rs
core/src/scheduler/processes.rs
core/src/scheduler/vm.rs
core/src/system.rs
interfaces/syscalls/src/block_on.rs
interfaces/syscalls/src/emit.rs
interfaces/syscalls/src/ffi.rs
interfaces/syscalls/src/interface_message.rs
interfaces/syscalls/src/lib.rs
interfaces/syscalls/src/response.rs
interfaces/tcp/src/lib.rs
kernel/cli/Cargo.toml
kernel/cli/src/main.rs
kernel/hosted-tcp/src/lib.rs
kernel/hosted-wasi/Cargo.toml
kernel/hosted-wasi/src/lib.rs
kernel/standalone/Cargo.toml
kernel/standalone/src/hardware.rs

`core` now depends on `syscalls-interface`.
`syscalls-interface` now contains `Pid`, `ThreadId` and `MessageId`.
I was hesitating between doing that and creating a new `primitives` crate.
I went for giving the role of "primitives container" to `syscalls-interface`.

Put type definitions in syscalls_interface and use them from core

---

Cargo.lock
core/Cargo.toml
core/src/id_pool.rs

Well, *almost* lock-free. It should only briefly locks once per thread at initialization.

Make IdPool lock-free again

---

core/src/scheduler/ipc.rs
core/src/scheduler/tests.rs
core/src/system.rs

Another thing I forgot to remove.
This was needed for WASI, but WASI needs to be implemented differently.
cc #165

Remove extrinsic system from core

---

core/src/scheduler/ipc.rs
interfaces/syscalls/src/emit.rs
interfaces/syscalls/src/ffi.rs
interfaces/syscalls/src/interface_message.rs

Cancelling a message and emitting an answer are inherently racy operations.
One process could cancel its message while the other one emits an answer at the same time. When emitting an answer returns an error, it can simply mean that the message has been cancelled.
This removes the possibility for these functions to return errors.

Make syscalls non racy

---

Cargo.lock
interfaces/time/Cargo.toml
interfaces/time/src/delay.rs
interfaces/time/src/instant.rs
interfaces/time/src/lib.rs
modules/Cargo.lock

Remove the `std` feature from `time-interface`.

Make time-interface always no_std

---

Cargo.lock
interfaces/hardware/src/lib.rs
interfaces/hardware/src/malloc.rs
interfaces/interface/src/lib.rs
interfaces/loader/src/lib.rs
interfaces/random/src/lib.rs
interfaces/stdout/src/lib.rs
interfaces/syscalls/Cargo.toml
interfaces/syscalls/src/emit.rs
interfaces/syscalls/src/lib.rs
interfaces/tcp/src/lib.rs
interfaces/time/src/lib.rs
interfaces/vulkan/build/main.rs
interfaces/window/src/lib.rs
modules/Cargo.lock

After #179, cleans up a bit the API of emitting a message in `syscalls` and allows sending messages split between slices.

Refactor emitting a message

---

core/src/id_pool.rs
core/src/native/collection.rs
core/src/scheduler/ipc.rs
core/src/scheduler/processes.rs
core/src/scheduler/vm.rs
core/src/system.rs
kernel/standalone/src/hardware.rs
kernel/standalone/src/random/rng.rs

We don't have backtraces in this freestanding environment, meaning that it is extremely annoying to get a kernel panic in `Result::unwrap` or `Option::unwrap`.
I think it's a good idea to manually call `panic!` for now.

Remove lots of unwraps in core & kernel

---

core/src/scheduler.rs
core/src/scheduler/extrinsics.rs
core/src/scheduler/ipc.rs

There is now a new layer between `processes.rs` and `ipc.rs` called `extrinsics.rs`. It translates syscalls made by the WASM modules into strongly-typed events.
In the future, if a syscall is bad, it will also purposefully crash the process. This is something that would be way to difficult to handle with the current code structure.
This makes the code way cleaner and understandable, and opens the door for #165 .

Split ipc.rs in two

---

Cargo.lock
interfaces/log/Cargo.toml
interfaces/log/src/ffi.rs
interfaces/log/src/lib.rs
interfaces/syscalls/src/emit.rs
kernel/hosted-log/src/lib.rs
modules/Cargo.lock
modules/arm-log/Cargo.toml
modules/arm-log/src/main.rs
modules/hello-world/src/main.rs
modules/ne2000/src/device.rs
modules/ne2000/src/main.rs
modules/x86-log/Cargo.toml
modules/x86-log/src/main.rs
modules/x86-pci/src/main.rs

Here's the hello world WASM after (without all the runtime garbage around):
```wast
(func $_ZN11hello_world4main17hbb01e2f79c3e02adE (type $t0)
(local $l0 i32)
get_global $g0
i32.const 48
i32.sub
tee_local $l0
set_global $g0
get_local $l0
i32.const 2
i32.store8 offset=15
get_local $l0
i32.const 25
i32.add
i32.const 1048600
i64.extend_u/i32
i64.const 51539607552
i64.or
i64.store align=1
get_local $l0
get_local $l0
i32.const 15
i32.add
i64.extend_u/i32
i64.const 4294967296
i64.or
i64.store offset=17 align=1
get_local $l0
i32.const 1
i32.store8 offset=16
i32.const 1054212
get_local $l0
i32.const 16
i32.add
i32.const 1
i32.or
i32.const 2
i32.const 0
i32.const 1
get_local $l0
i32.const 40
i32.add
call $_ZN27redshirt_syscalls_interface3ffi12emit_message17h508280f1400e36efE
drop
get_local $l0 …
```

Remove the overhead of logging as much as possible

---

core/src/scheduler/ipc.rs
core/src/scheduler/tests/basic_module.rs
core/src/scheduler/tests/emit_not_available.rs
core/src/scheduler/tests/emit_reserved_pid.rs
core/src/scheduler/tests/trapping_module.rs
core/src/scheduler/tests/wasm_recv_interface_msg.rs
core/src/system.rs

cc #1 
After #215, also makes the core "multithreaded", except that we're cheating and not implementing `Sync` or `Sync`.

Make Core methods take &self

---

.github/node-deploy-kube-config.yml
modules/Cargo.lock
modules/p2p-loader/Cargo.toml
modules/p2p-loader/src/bin/modules-loader.rs
modules/p2p-loader/src/bin/passive-node.rs
modules/p2p-loader/src/lib.rs

Pass a private key to Kubernetes so that the bootnode's public key stops changing.
Note: yeah the private key is clearly visible in the repo (it's only encoded in base64). It doesn't really matter, as you can't actually achieve anything with a MITM attack apart from denial of service. If this gets serious, I'll switch to a key that is actually secret.

Fix the key of the bootnode

---

.github/workflows/ci.yml
core-proc-macros/src/lib.rs
kernel/standalone/src/kernel.rs

Allows putting the `p2p-loader` in the standalone kernel.

Make build_wasm_module! accept a second parameter

---

kernel/standalone/src/arch.rs
kernel/standalone/src/arch/arm.rs
kernel/standalone/src/arch/arm/executor.rs
kernel/standalone/src/arch/x86_64.rs
kernel/standalone/src/arch/x86_64/apic.rs
kernel/standalone/src/arch/x86_64/executor.rs
kernel/standalone/src/hardware.rs
kernel/standalone/src/kernel.rs
kernel/standalone/src/main.rs
kernel/standalone/src/random/rng.rs
kernel/standalone/src/time.rs

Adds a `PlatformSpecific` trait in the `arch` module of the standalone kernel.
This allows properly defining how the functions in `arch` must behave.

Add a PlatformSpecific trait

---

Cargo.lock
x86_64-multiboot2.json

cc #73
> The proper solution is stack probes, but I don't know how technically possible that is.
Actually quite easy. The `__rust_probestack` function is provided by `compiler_builtins`.
Note that this doesn't add any protection. We still need to properly setup paging.

Enable stack probes on x86

---

kernel/standalone/src/arch/x86_64/boot.S

Fix #72 
Does paging a bit better, and doesn't require support for 1G pages anymore.
We identity-map 4GiB of memory during the boot process.

Don't require 1G pages

---

arm-freestanding.ld

Eventually the code should be PIC (cc #282) but in the meanwhile this fixes the address where the kernel gets loaded.

Fix the start address on raspi

---

Cargo.lock
core/Cargo.toml
core/src/extrinsics/wasi.rs
modules/rpi-framebuffer/src/main.rs
modules/x86-log/src/main.rs

Implements `fd_write` again. Allows seeing the panic messages of modules without the module having to call `std::panic::set_hook`.
As such, I also removed the calls to `set_hook`.

Implement fd_write for WASI

---

kernel/standalone/src/arch/x86_64.rs
kernel/standalone/src/arch/x86_64/ap_boot.rs
kernel/standalone/src/arch/x86_64/apic/timers.rs

Uses the PIT to determine how many RDTSC ticks happen per second.
Now that the timer resolution is correct, the associated processors initialization properly works for all processors.

Benchmark the RDTSC clock with the PIT

---

kernel/standalone/src/kernel.rs

No longer show a panic message when a secondary processor reaches `Kernel::run`.
This is benign, but was always annoying.

Don't make APs panic in kernel::run

---

interfaces/syscalls/src/block_on.rs

It's amazing.
When I wrote this code I somehow felt that there was something wrong but couldn't pinpoint what.
And earlier when debugging a panic that was coming from the `state.message_ids[index] = ...` below, I read this code multiple times and still couldn't figure out what was wrong. It's only after I added `println!`s everywhere that I realized that we would never enter the `if`.

Fix bug in register_message_waker

---

.github/workflows/ci.yml
core/src/module.rs
core/src/system.rs
interfaces/loader/src/ffi.rs
kernel/cli/Cargo.toml
kernel/cli/src/main.rs
kernel/hosted-tcp/src/lib.rs
modules/Cargo.lock
modules/p2p-loader/Cargo.toml
modules/p2p-loader/Dockerfile
modules/p2p-loader/src/bin/modules-loader.rs
modules/p2p-loader/src/bin/passive-node.rs
modules/p2p-loader/src/lib.rs
modules/p2p-loader/src/notifier.rs

A few changes:
- The CLI kernel has been improved and now accepts paths to foreground modules and background modules, or hashes of foreground modules and background modules. When a hash is passed, it is loaded from the peer-to-peer network.
- The passive node will now watch files in the `../target/wasm32-wasi/release` directory for Wasm files and automatically push them on the DHT.
It works in the sense that small files do work, but large files don't get through to the bootstrap node because of the size limit. Libp2p-kad unfortunately doesn't let you configure the maximum message size at the moment.

Work on the p2p loader

---

Cargo.lock
core/Cargo.toml
core/src/extrinsics/wasi.rs

cc #323 
Fixes a couple bugs, implements many functions, and implements some kind of stub for a virtual file system for WASI programs.
I've always had in mind to try provide backwards compatibility for existing programs thanks to the efforts of WASI. However I don't really know what to do with programs that read/write files on the filesystem.
As a temporary solution, I've added some kind of poorly-implemented virtual read-only filesystem. This is very much a hack in order to try make DOOM work.

More work on WASI to support DOOM

---

.github/workflows/ci.yml
core/src/extrinsics/wasi.rs
kernel/standalone/src/arch.rs
kernel/standalone/src/arch/arm.rs
kernel/standalone/src/arch/x86_64.rs
kernel/standalone/src/kernel.rs

This is mostly a celebration PR for async functions being able to work in `no_std` contexts :tada:

Remove PlatformSpecific::block_on

---

Cargo.lock
core/Cargo.toml
core/src/extrinsics/wasi.rs

- The `clock_time_get` function now properly uses the `system-time` interface for the real time clock.
- Turns a lot of panics into regular errors that will trigger a `ProgramCrash`.

Make WASI handlers more robust

---

kernel/standalone-builder/src/image.rs

Makes GRUB not show a warning about being unable to load graphics mode.

Add some options to GRUB

---

core/src/scheduler/extrinsics.rs
core/src/scheduler/extrinsics/calls.rs
core/src/scheduler/ipc/notifications_queue.rs
interfaces/syscalls/src/block_on.rs

- That assertion in `syscalls` is wrong. The size can differ between the two lists, since we remove elements from the wakers list but only zero elements in the messages list.
- In the kernel, we would discard zero'ed entries in the messages list. This is wrong, as we have to send back to the user the position of the entry in the list. By discarding zero'ed entries, that position would be wrong.

Fix two bugs related to notifications delivery

---

modules/p2p-loader/src/lib.rs

Right now if we start loading the same module multiple times, the second and further will just stay in limbo and never finish.

Allow loading the same module multiple times

---

Cargo.lock
kernel/standalone/Cargo.toml
kernel/standalone/src/arch.rs
kernel/standalone/src/arch/x86_64/apic/local.rs
kernel/standalone/src/arch/x86_64/executor.rs
kernel/standalone/src/arch/x86_64/interrupts.rs

Unfortunately we can't directly calle `Waker::wake()`, as waking might uses mutexes.

Ensure interrupts can't deadlock

---

kernel/standalone/src/arch/x86_64.rs
kernel/standalone/src/arch/x86_64/apic/timers.rs

Timers in #394 weren't actually working because I misunderstood the `drain_filter` method.
Fix #379

Small fixes to timers

---

kernel/standalone/src/pci/pci.rs

This small adjustment is necessary to make the kernel work on my real-life machine.

Small PCI adjustment

---

kernel/standalone/src/arch.rs
kernel/standalone/src/arch/arm.rs
kernel/standalone/src/arch/riscv.rs
kernel/standalone/src/arch/x86_64.rs
kernel/standalone/src/kernel.rs
kernel/standalone/src/pci/native.rs

The PCI interface makes it possible to get notified when the PCI device generates an interrupt, but this was previously implemented as a stub. This PR properly implements this.
Note that the implementation isn't very clean, as *all* IRQs will wake up *all* PCI devices drivers. But at least it will work.
Implementing it properly would require analyzing and executing the AML tables, which is notoriously painful.

Make waiting for a PCI IRQ work

---

kernel/standalone/src/arch/x86_64.rs
kernel/standalone/src/kernel.rs

I don't remember why this wasn't already the case, but here's a PR that enables running the kernel from multiple CPUs simultaneously.
Apart from the simple bugfix in `NextIrqFuture`, everything seems to work flawlessly.

Make standalone kernel multithreaded

---

README.md

The service has been dead for some time now, and the chances of it working again soon look slim.
https://github.com/srijs/deps.rs/issues/41
We can always restore the badge when it works again.

Remove deps.rs badge from README

---

kernel/standalone/src/kernel.rs
modules/p2p-loader/src/bin/modules-loader.rs
modules/p2p-loader/src/lib.rs

- Now properly use the modules loader on the standalone kernel as well.
- Removes the hacky 5 seconds delay before initialization. Instead we now register the loader interface only when we're connected to the first peer.

Improvements to p2p-loader

---

.maintain/node-deploy-kube-config.yml
kernel/standalone/src/kernel.rs
modules/p2p-loader/src/bin/passive-node.rs
modules/p2p-loader/src/lib.rs

I didn't update the `PeerId`s because I'm too lazy to figure out what they will be. After deployment, will read them from the nodes and open a second PR.

Prepare a second bootnode

---

.maintain/node-deploy-kube-config.yml
modules/p2p-loader/src/lib.rs

cc #482 
Considering that DigitalOcean lets me assign specific IPs to specific nodes, this PR makes bootnodes derive their private key based on the name of the node.
In other words, even if pods jump between nodes, the mapping between IP address and peer ID will stay the same.

More Kubernetes work

---

modules/Cargo.lock
modules/p2p-loader/Cargo.toml
modules/p2p-loader/src/lib.rs

Updates to libp2p 0.20.2, switches to using `yamux`, and some small changes.
The switch to yamux is a fix attempt for https://github.com/tomaka/redshirt/issues/330

Improvements to the p2p-loader

---

Cargo.lock
core/Cargo.toml
core/src/system.rs

This seems quite important considering that it is read all the time.
The reason why it isn't already an atomic is that `AtomicU64` isn't available on all platforms. The cool `atomic` library solves this problem.

Make the loader_pid an atomic variable

---

kernel/standalone/src/arch/x86_64.rs
kernel/standalone/src/arch/x86_64/boot.rs
kernel/standalone/src/main.rs

Removes the dependency on the `global_asm` feature (cc #300), and removes the `#[no_mangle]` requirement on `after_boot`.

Rewrite _start to be a naked function

---

kernel/standalone/src/arch/x86_64/apic/local.rs
kernel/standalone/src/arch/x86_64/apic/timers.rs

- Removes the `TODO: has_cpuid()` checks, as this method is planned to be removed. If `cpuid` isn't supported then we'll get a panic for illegal instruction anyway, and having an `assert` failure doesn't change much.
- Removes the constant-rate APIC timer check, as it's not supported by AMD.
- Checks for TSC support.

Minor changes regarding CPUID

---

kernel/standalone/src/arch/x86_64.rs
kernel/standalone/src/arch/x86_64/ap_boot.rs
kernel/standalone/src/arch/x86_64/apic/timers.rs
kernel/standalone/src/time.rs

Probably one of the biggest stupidities I've done so far. `register_timer_at` and `register_timer_after` were mixed.
If 20 seconds after the system start-up you called `Delay::new(Duration::from_secs(1))`, then it would actually wait for 21 seconds.
This is a huge fix that fixes a lot of things behaving in a weird way.

Various fixes to timers

---

kernel/standalone/src/kernel.rs

Unfortunately it still doesn't work great (#330), and when the module isn't found on the DHT, the kernel just panics. At the moment let's just not load anything.

Revert automatically loading a module

---

kernel/standalone/src/arch/x86_64.rs
kernel/standalone/src/arch/x86_64/apic/local.rs
kernel/standalone/src/kernel.rs

https://github.com/tomaka/redshirt/issues/459 is maybe fixed
Fixes notably two things:
- We weren't calling `local_apic.init_local()` on the main CPU.
- A wrong flag when sending IPIs :facepalm:

A couple of associated-processors-related fixes

---

kernel/standalone/src/pci/pci.rs

I had removed this check because I thought this was a faulty situation resulting from not handlint 64bits addresses at the time.
In practice, the I/O ports values do go above 0xffff on my Thinkpad X1.

Restore clamping to 0xffff for PCI I/O ports

---

kernel/standalone/src/kernel.rs
modules/Cargo.lock
modules/http-server/Cargo.toml
modules/http-server/src/main.rs

Fix #525 
One can now connect the Prometheus scraper to the kernel and see for example the CPU usage over time:
(CPU 1 isn't visible above because of [this todo](https://github.com/tomaka/redshirt/blob/7d80254aec50967fee95209f9f788a89501efaee/kernel/standalone/src/kernel.rs#L153-L155))

Make HTTP server expose kernel metrics

---

Cargo.lock
core/Cargo.toml
interfaces/syscalls/Cargo.toml
kernel/standalone/Cargo.toml
kernel/standalone/src/arch/x86_64/apic/timers.rs
modules/Cargo.lock
modules/network-manager/Cargo.toml
modules/pci-printer/Cargo.toml

The behavior of `drain_filter` has changed in this release:
https://github.com/rust-lang/hashbrown/issues/186

Update to hashbrown 0.9

---

kernel/standalone-builder/res/specs/riscv-hifive.ld
kernel/standalone/src/arch/riscv.rs
kernel/standalone/src/arch/riscv/interrupts.rs

Removes all the `global_asm!` usages.

Make RISC-V compile again

---

kernel/standalone/src/arch/riscv.rs
kernel/standalone/src/arch/riscv/executor.rs
kernel/standalone/src/arch/riscv/interrupts.rs
kernel/standalone/src/arch/riscv/log.rs

The RISC-V kernel doesn't actually work because there's way too little memory (16 kiB) on the HiFive, which is what we target by default.
However, here are some warning fixes and replacement of `llvm_asm!` with `asm!`.

Some fixes to the RISC-V kernel

---

kernel/standalone/src/arch/arm.rs
kernel/standalone/src/arch/arm/executor.rs
kernel/standalone/src/arch/arm/log.rs
kernel/standalone/src/arch/arm/time_aarch64.rs
kernel/standalone/src/arch/arm/time_arm.rs
kernel/standalone/src/arch/riscv.rs
kernel/standalone/src/main.rs

Removes usage of the `llvm_asm` feature.
cc #300

Replace all remaining llvm_asm! with asm!

---

core-proc-macros/src/lib.rs
kernel/standalone-builder/Cargo.lock
kernel/standalone-builder/Cargo.toml
kernel/standalone-builder/src/bin/main.rs
kernel/standalone-builder/src/build.rs
kernel/standalone-builder/src/lib.rs
kernel/standalone/src/arch/arm.rs
kernel/standalone/src/arch/riscv.rs
kernel/standalone/src/arch/x86_64/boot.rs
kernel/standalone/src/lib.rs

Close #689 
Before this PR, the standalone kernel is cross-platform. It uses only the build target (e.g. `x86_64-unknown-multiboot2`) to determine which environment to expect, and documents it.
The kernel also assumes that the linker will provide the `__bss_start` and `__bss_end` symbols. Again, this is documented.
After this PR, the standalone kernel is no longer a binary but a library. It provides a macro called `__gen_boot!` that generates the code necessary to boot the kernel. The difference compared to now is that this macro can be passed more parameters than just the target, which will result in less guessing.
For example, the `__bss_start` and `__bss_end` symbols are now explicitly provided as parameters to the macro.
The user, here the standalone kernel builder, at the same time …

Turn the standalone kernel into a library

---

kernel/standalone-builder/res/specs/aarch64-freestanding.json
kernel/standalone-builder/res/specs/arm-freestanding.json
kernel/standalone-builder/res/specs/riscv-hifive.json
kernel/standalone-builder/res/specs/x86_64-multiboot2.json
kernel/standalone/src/arch/arm.rs

This fixes the Rust compiling segfaulting when compiling for Raspberry Pi.

Update target specs for recent Rust versions

---

.github/dependabot.yml

We've now more or less caught up with outdated dependencies.

Cleanup dependabot rules

---

kernel/standalone/src/arch/x86_64/boot.rs

I think that this is what causes of the issues of the kernel not booting after some random changes (e.g. https://github.com/tomaka/redshirt/pull/717#issuecomment-755178969), and it is also a reasonable explanation of why theses issues were happening.

Fix bad x86 stack alignment

---

Cargo.lock
interfaces/syscalls/Cargo.toml
kernel/core/Cargo.toml
programs/Cargo.lock

It has finally merged this 1.5 years old PR that adds `no_std` support :tada:

Move to upstream `slab`
